# Generated by Django 5.1.4 on 2025-01-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=100)),
                ("recipe_desription", models.TextField()),
                ("recipe_img", models.ImageField(upload_to="images/recipe")),
            ],
        ),
    ]
