# Generated by Django 5.1.4 on 2025-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_student_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
