# Generated by Django 5.1.4 on 2025-01-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_student_dob_alter_student_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=50)),
                ("car_id", models.IntegerField()),
                ("speed", models.IntegerField(default=0)),
            ],
        ),
    ]
